language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-angular-rails' ]; then cd .. && eval "mv $currentfolder generator-angular-rails" && cd generator-angular-rails; fi
